// This file is auto-generated by @hey-api/openapi-ts

export const $LeaderboardEntryDto = {
    type: 'object',
    properties: {
        rank: {
            type: 'number',
            example: 1
        },
        address: {
            type: 'string',
            example: '0x1234abcd5678ef901234abcd5678ef901234abcd'
        },
        totalDeposited: {
            type: 'string',
            example: '150.42',
            description: 'Total deposited amount (stringified Decimal)'
        },
        totalWithdrawn: {
            type: 'string',
            example: '50.00',
            description: 'Total withdrawn amount (stringified Decimal)'
        },
        totalCompounded: {
            type: 'string',
            example: '75.12',
            description: 'Total compounded amount (stringified Decimal)'
        },
        totalCompoundCount: {
            type: 'number',
            example: 12
        },
        referralEarningsUnits: {
            type: 'string',
            example: '24.5',
            description: 'Referral earnings in contract units (stringified Decimal)'
        },
        lastActiveAt: {
            type: 'object',
            example: '2025-01-15T10:30:00.000Z',
            nullable: true,
            description: 'ISO timestamp of last activity',
            format: 'date-time'
        }
    },
    required: ['rank', 'address', 'totalDeposited', 'totalWithdrawn', 'totalCompounded', 'totalCompoundCount', 'referralEarningsUnits', 'lastActiveAt']
} as const;

export const $UserReferralDto = {
    type: 'object',
    properties: {
        referee: {
            type: 'string',
            example: '0xabcdefabcdefabcdefabcdefabcdefabcdefabcd'
        },
        totalUnitsRewarded: {
            type: 'string',
            example: '12.75',
            description: 'Total reward units as string'
        },
        lastRewardAt: {
            type: 'object',
            example: '2025-01-15T10:30:00.000Z',
            nullable: true,
            format: 'date-time'
        },
        totalRewards: {
            type: 'number',
            example: 5
        },
        buyAmount: {
            type: 'string',
            example: '150.42',
            description: 'Total amount of tokens bought by referee (stringified Decimal)'
        }
    },
    required: ['referee', 'totalUnitsRewarded', 'lastRewardAt', 'totalRewards', 'buyAmount']
} as const;

export const $TvlDataPointDto = {
    type: 'object',
    properties: {
        timestamp: {
            type: 'string',
            example: '2025-01-15T10:30:00.000Z',
            description: 'ISO timestamp of snapshot',
            format: 'date-time'
        },
        tvl: {
            type: 'string',
            example: '1000.5',
            description: 'Total value locked in ETH (string)'
        }
    },
    required: ['timestamp', 'tvl']
} as const;

export const $TotalValueLockedDto = {
    type: 'object',
    properties: {
        totalDeposited: {
            type: 'string',
            example: '5000.123',
            description: 'Cumulative total of all deposits that entered the contract (stringified Decimal)'
        }
    },
    required: ['totalDeposited']
} as const;

export const $EventPayload = {
    type: 'object',
    properties: {
        type: {
            type: 'string',
            example: 'user:update',
            description: 'Event type (e.g. user:update, tvl:update)'
        },
        data: {
            type: 'object',
            description: 'Arbitrary event payload',
            additionalProperties: true,
            example: {
                address: '0x1234abcd5678ef901234abcd5678ef901234abcd',
                weekStart: '2025-01-13T00:00:00.000Z'
            }
        }
    },
    required: ['type', 'data']
} as const;