// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ApiControllerGetLeaderboardData, ApiControllerGetLeaderboardResponse, ApiControllerGetUserLeaderboardDataData, ApiControllerGetUserLeaderboardDataResponse, ApiControllerGetUserReferralsData, ApiControllerGetUserReferralsResponse, ApiControllerGetTvlChartData, ApiControllerGetTvlChartResponse, ApiControllerGetTotalValueLockedResponse, SseGatewayStreamResponse } from './types.gen';

/**
 * Get leaderboard
 * @param data The data for the request.
 * @param data.limit Number of entries (1-1000)
 * @param data.offset Pagination offset (0-100000)
 * @returns LeaderboardEntryDto List of users ordered by totalDeposited
 * @throws ApiError
 */
export const apiControllerGetLeaderboard = (data: ApiControllerGetLeaderboardData = {}): CancelablePromise<ApiControllerGetLeaderboardResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/leaderboard',
    query: {
        limit: data.limit,
        offset: data.offset
    },
    errors: {
        400: 'Invalid pagination parameters'
    }
}); };

/**
 * Get user position in leaderboard
 * @param data The data for the request.
 * @param data.address Ethereum address of the user
 * @returns LeaderboardEntryDto User statistics
 * @throws ApiError
 */
export const apiControllerGetUserLeaderboardData = (data: ApiControllerGetUserLeaderboardDataData): CancelablePromise<ApiControllerGetUserLeaderboardDataResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/leaderboard/{address}',
    path: {
        address: data.address
    },
    errors: {
        400: 'Invalid address format',
        404: 'User not found'
    }
}); };

/**
 * Get user referrals
 * @param data The data for the request.
 * @param data.address Ethereum address of the referrer
 * @returns UserReferralDto Referrals and reward statistics
 * @throws ApiError
 */
export const apiControllerGetUserReferrals = (data: ApiControllerGetUserReferralsData): CancelablePromise<ApiControllerGetUserReferralsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/referrals/{address}',
    path: {
        address: data.address
    },
    errors: {
        400: 'Invalid address format'
    }
}); };

/**
 * Get TVL chart
 * @param data The data for the request.
 * @param data.limit Maximum number of points (1-10000)
 * @param data.from Start date (ISO format)
 * @param data.to End date (ISO format)
 * @returns TvlDataPointDto TVL snapshots for the selected range
 * @throws ApiError
 */
export const apiControllerGetTvlChart = (data: ApiControllerGetTvlChartData = {}): CancelablePromise<ApiControllerGetTvlChartResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/tvl-chart',
    query: {
        limit: data.limit,
        from: data.from,
        to: data.to
    },
    errors: {
        400: 'Invalid query parameters'
    }
}); };

/**
 * Get Total Value Locked
 * Returns cumulative total of all deposits that entered the contract
 * @returns TotalValueLockedDto Total Value Locked (cumulative deposits)
 * @throws ApiError
 */
export const apiControllerGetTotalValueLocked = (): CancelablePromise<ApiControllerGetTotalValueLockedResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/total-value-locked'
}); };

/**
 * Subscribe to the server-sent events stream
 * @returns EventPayload Event stream in Server-Sent Events format
 * @throws ApiError
 */
export const sseGatewayStream = (): CancelablePromise<SseGatewayStreamResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/events'
}); };