// This file is auto-generated by @hey-api/openapi-ts

export type LeaderboardEntryDto = {
    rank: number;
    address: string;
    /**
     * Total deposited amount (stringified Decimal)
     */
    totalDeposited: string;
    /**
     * Total withdrawn amount (stringified Decimal)
     */
    totalWithdrawn: string;
    /**
     * Total compounded amount (stringified Decimal)
     */
    totalCompounded: string;
    totalCompoundCount: number;
    /**
     * Referral earnings in contract units (stringified Decimal)
     */
    referralEarningsUnits: string;
    /**
     * ISO timestamp of last activity
     */
    lastActiveAt: {
        [key: string]: unknown;
    } | null;
};

export type UserReferralDto = {
    referee: string;
    /**
     * Total reward units as string
     */
    totalUnitsRewarded: string;
    lastRewardAt: {
        [key: string]: unknown;
    } | null;
    totalRewards: number;
    /**
     * Total amount of tokens bought by referee (stringified Decimal)
     */
    buyAmount: string;
};

export type TvlDataPointDto = {
    /**
     * ISO timestamp of snapshot
     */
    timestamp: string;
    /**
     * Total value locked in ETH (string)
     */
    tvl: string;
};

export type TotalValueLockedDto = {
    /**
     * Cumulative total of all deposits that entered the contract (stringified Decimal)
     */
    totalDeposited: string;
};

export type EventPayload = {
    /**
     * Event type (e.g. user:update, tvl:update)
     */
    type: string;
    /**
     * Arbitrary event payload
     */
    data: {
        [key: string]: unknown;
    };
};

export type ApiControllerGetLeaderboardData = {
    /**
     * Number of entries (1-1000)
     */
    limit?: number;
    /**
     * Pagination offset (0-100000)
     */
    offset?: number;
};

export type ApiControllerGetLeaderboardResponse = Array<LeaderboardEntryDto>;

export type ApiControllerGetUserLeaderboardDataData = {
    /**
     * Ethereum address of the user
     */
    address: string;
};

export type ApiControllerGetUserLeaderboardDataResponse = LeaderboardEntryDto;

export type ApiControllerGetUserReferralsData = {
    /**
     * Ethereum address of the referrer
     */
    address: string;
};

export type ApiControllerGetUserReferralsResponse = Array<UserReferralDto>;

export type ApiControllerGetTvlChartData = {
    /**
     * Start date (ISO format)
     */
    from?: string;
    /**
     * Maximum number of points (1-10000)
     */
    limit?: number;
    /**
     * End date (ISO format)
     */
    to?: string;
};

export type ApiControllerGetTvlChartResponse = Array<TvlDataPointDto>;

export type ApiControllerGetTotalValueLockedResponse = TotalValueLockedDto;

export type SseGatewayStreamResponse = EventPayload;

export type $OpenApiTs = {
    '/api/leaderboard': {
        get: {
            req: ApiControllerGetLeaderboardData;
            res: {
                /**
                 * List of users ordered by totalDeposited
                 */
                200: Array<LeaderboardEntryDto>;
                /**
                 * Invalid pagination parameters
                 */
                400: unknown;
            };
        };
    };
    '/api/leaderboard/{address}': {
        get: {
            req: ApiControllerGetUserLeaderboardDataData;
            res: {
                /**
                 * User statistics
                 */
                200: LeaderboardEntryDto;
                /**
                 * Invalid address format
                 */
                400: unknown;
                /**
                 * User not found
                 */
                404: unknown;
            };
        };
    };
    '/api/referrals/{address}': {
        get: {
            req: ApiControllerGetUserReferralsData;
            res: {
                /**
                 * Referrals and reward statistics
                 */
                200: Array<UserReferralDto>;
                /**
                 * Invalid address format
                 */
                400: unknown;
            };
        };
    };
    '/api/tvl-chart': {
        get: {
            req: ApiControllerGetTvlChartData;
            res: {
                /**
                 * TVL snapshots for the selected range
                 */
                200: Array<TvlDataPointDto>;
                /**
                 * Invalid query parameters
                 */
                400: unknown;
            };
        };
    };
    '/api/total-value-locked': {
        get: {
            res: {
                /**
                 * Total Value Locked (cumulative deposits)
                 */
                200: TotalValueLockedDto;
            };
        };
    };
    '/events': {
        get: {
            res: {
                /**
                 * Event stream in Server-Sent Events format
                 */
                200: EventPayload;
            };
        };
    };
};